language: minimal
services:
- docker
before_install:
- docker pull dm874/deploy
stages:
- build-publish
- deploy-migrations
- deploy-app
jobs:
  include:
  - stage: build-publish
    script: docker build -t jolie-exec . && sh deployment/publish_jolie_exec.sh
  - stage: build-publish
    script: docker build -t migrations migrations/ && sh deployment/publish_migrations.sh
  - stage: deploy-migrations
    script: sh deployment/deploy_migrations.sh
  - stage: deploy-app
    script: sh deployment/deploy_jolie_exec.sh
env:
  global:
  - secure: Vt2KIY8Wfp1SrCQdeEFPU5Sy2d2g8McKqOfxH0T35U9G4pORKEotIWpw0AIRTO9oJzMGzUITyWLoAmk+c7pG6kSXLDBFS9LdrfojxogF0VdcCmEDkeYqSZrNtVshGE3+sPXVA00cg1hWt5yuH5X1lDZ2jl88U78TSIbfzjGSCiEAjFqsnPjtwrtNQPqn4XviWSuxnHfQTEgFzcZb8JrtphAqoRGYCwTpEnVXTemWwxH+aOUiyimFtmeJMqkaygr0/P6agqF1OoB+Nmq7qkPVPZGN/mPWuwFJz6Km9ly2EO8HRiuaoB1hSdmVBMUtcPOy0rcsM1MAI0Co/pnQxKBRqGGuUiyjM5tG0wSpc0aJvoAMNrWOIssG0O1aDL/d30JqfkChVuQvFmjTCFNMLYMRIc+rd+N3IOJJt6Yt1Njcp9hCLWKN5x6+4fKzb2L540/7j9Pliqe8D5tWR45HKa3HVW4T/wO/auJKCIizPFswUFNcVhlg/CGa7o4d6XVlHrw8GyW46S0mf5iuz7JXSDyolzYN0lnoR67aSaLMKo9vdbtLMoC+XXeYiius1ahQCn8NbmhwBsQRw3OEppPkkwvvEhZ8bQELP2jJntrT4xELzyKujWiwdKraqrqq2fk4mzfSCn/89cv3hqPJWyxhHUFgyGWMllxS8EMCfpYsXyqNkBY=
  - secure: AI0kDE/OYNP9UUYT/MUPhMBzYSG347Q2fuqfzSCbUL64D00yaTGoMdA82kE7F3vLw7WMOzLqF6Ly2hUg/7RvmGO8DkzRLyocvNl2vDTqeox1pBuJLXaJM2eogtwdjcC1jk+jpqojcrXwojrDvQl3wjzTa/uQOB/URvv2kDkBUPsaFvVRpfp/3hRsGd3C2ToTS9vvOY9uWpMJ//mU1T3gWXs1L6x97N6jFXQ9L5MCmhrHbcap9TmKvqp7hVsK5fpn5LcVu8+sYcxt0oogzmpDmHehDfU7TXYEbmLjrfPkVwyLWzkF00bdc3OenYSH520Z81IO0Fy80d83RFdZ7bHw6puWwPlMu/+fqlRV1D1Fah/ju3mL+CiDjBMQRff2YpvfH5e5YbJzl8vv1yeQy3GD68WMQ2LX/xXoTe2j8Vbr2Tnm2rp8IcgK3bgre/CwON8gWS6w+SbpCORKgL9fTZozKifbPMhiqoZsXO8WfneDjoaMy826For90/qedILdVCxo+y2Lw8cG13NI7WtyZwZC4gwjBQmKH/JJiOFglQV/8XuLSu9sbPaySKLF9hL4H/GLce8o0pGdWf2DmvQyEL+NAJs3MzXpmIezsQTc/EhsnsJ/0G1SyHnPZ9BrRt6Kt68CXidnE8bc2EzxzXLdn5QqJ+/8a/Y6jJJ5nusSfYaybMc=
  - secure: m77IbQU2UYlzGU2NS2skJCME/xGEHknbZ2uMvyv/KsPDWcCfZAuSWvjp2iXoQTm1sEw/jOLALIBrp6TW1dBvy0HKniCTEgSWJNBVt5CG1jpfpmaF/VpHHLCHh8jGIFLqLI/J75LRwB2v4tF7WRxKR3Q32R+O3wpRLDJ/LtSKpo5gN40k5IBouzBcIkutXUXUmt47TwL7rI9tWFuu+VBFCipUUEilaJTBdGfgbyFQVckv2qhoNaw3rsLOayDanl3iJyu/sjwzVVZj1upukdRktOpm6u+omRTCJq9Hp+P7y+EyF04Q6NL6RiN82UcSo8ocdFIjb4bGLiyhoLzomb1Ys6r2uLYAraO6v/tZVeSJR2xt8UVjr7JGEhFVNUeJntE3EpuJqpo8yNxIxInqFyvT+rrRBItjOIuaCT0/v9yI0ZrytxfWBGvRGDVQyRL3B3ofG/d5FC8nnU9C9akFYefNsFTUzRXlm4CUxrQHOJNWNXpmyzbc5SXZB95oHhSsG3e5QCDg1CyXjlkVTLw9jfF8192w/soThSwBC66GYs/shn7NaWYZNUTvxKVaqyblRc8i6UBq/mqQO7wCKf6FPgBTMs7tyMiwwi8gDfBLwRHtJZcTzmELcAhf95tJZkLZX2DabsppdJfF1XxQhhpSYprCwGOZZUdRPndx1aU88JzNdlg=
