apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jolie-exec
spec:
  replicas: 1
  serviceName: "jolie-exec"
  selector:
    matchLabels:
      app: jolie-exec
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: router
    spec:
      initContainers:
        - name: migrations-container
          image: dm875/jolie-exec-migrations
          imagePullPolicy: Always
          envFrom:
            - secretRef:
              name: db-secrets
      containers:
        - name: jolie-exec-container
          image: dm874/jolie-exec:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: db-secrets
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "16Gi"
              cpu: "500m"
            limits:
              memory: "80Gi"
              cpu: "1000m"
